### ISSUE TITLE
Reconsider python package dependency management

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1140]
### What needs to get done

Currently we run pip (up to) 4 times, and in a way that can be counterintuitive to the user. Package sets can override each other, and explicitly frozen package versions can be ignored.

Ideally, we'd have a way to specify this all to be calculated in a single `pip` command that:

- Only installs binary packages for those specified as binaries (and their dependencies?)
- Fails on package conflicts
- Doesn't overwrite pinned versions

### Why it needs to get done

The current method has evolved over years to become counterintuitive and sometimes problematic (see #1135). However, changes related to this could cause compatibility issues, so they should be done carefully and deliberately. As such, a rethink of this would need to come with a major version release if we decide to do it.

**Comment by syu-w** [comment]
Notice we sometime need to install binary package first then reinstall it from sources.

**Comment by syu-w** [comment]
`poetry` should be fine, but I am not sure if we want to use it as base package that install in all build system.

**Comment by benhoyt** [comment]
@lengau, @kian99 is [running into a related issue](https://github.com/canonical/operator/issues/985) where they have `ops==2.4.1` pinned in the charm's requirements.txt, but one of the libraries also says `ops>=2.0.0`. This isn't a conflict, but `charmcraft pack` fails with the following error:

```
Double requirement given: ops==2.4.1 (from -r requirements.txt (line 1)) (already in ops>=2.0.0, name='ops')                                     
```

I believe this is happening because `charmcraft pack` is using an older version of pip that doesn't yet use [pip's new dependency resolver that appeared in 20.3](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html). I've tried this locally with pip 22.0 and that handles the above "double requirement" fine.

Can the charmcraft.yaml specify a newer pip version to use, or do you have any other suggested workaround?
