### ISSUE TITLE
`charmcraft pack` fails with a false positive on the summary check

### ISSUE THREAD

**Issue by DnPlas** [canonical/charmcraft#1568]
### Bug Description

Running `charmcraft pack` on a charm with a [`charmcraft.yaml`](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/charmcraft.yaml) file without a summary fails with msg:

```
charmcraft pack -v
Starting charmcraft, version 2.5.5.post96+g26e3f02                                                                                 
Logging execution to '/home/dplascen/.local/state/charmcraft/log/charmcraft-20240301-124953.845091.log'                            
Bad charmcraft.yaml content:
- ensure this value has at most 78 characters (in field 'summary')                                    
Full execution log: '/home/dplascen/.local/state/charmcraft/log/charmcraft-20240301-124953.845091.log'     
```

### To Reproduce

1. Install charmcraft from latest/edge channel
2. `chamrcraft pack -v` a charm with no `summary` in its `charmcraft.yaml` file. You could use [this one](https://github.com/canonical/istio-operators/tree/main/charms/istio-pilot)
3. Observe the error

### Environment

* Ubuntu 20.04 and 22.04
* charmcraft latest/edge

### charmcraft.yaml

```shell
type: charm
bases:
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
    run-on:
    - name: "ubuntu"
      channel: "20.04"
parts:
  charm:
    charm-python-packages: [setuptools, pip, jsonschema, cryptography, cffi]
    build-packages: [git, rustc, cargo, libffi-dev, libssl-dev, pkg-config]
  istioctl:
    plugin: dump
    source: https://github.com/istio/istio/releases/download/1.17.3/istioctl-1.17.3-linux-amd64.tar.gz
    source-type: tar
```

### Relevant log output

```shell
charmcraft pack -v
Starting charmcraft, version 2.5.5.post96+g26e3f02                                                                                 
Logging execution to '/home/dplascen/.local/state/charmcraft/log/charmcraft-20240301-124953.845091.log'                            
Bad charmcraft.yaml content:
- ensure this value has at most 78 characters (in field 'summary')                                    
Full execution log: '/home/dplascen/.local/state/charmcraft/log/charmcraft-20240301-124953.845091.log'
```

**Comment by lengau** [comment]
Thanks for the report!

The error message is a bit misleading, but the failure is because the `metadata.yaml` file has a 90 character summary. This matches what we have in snapcraft, but since the charm is already published on charmhub and it's not breaking there, we may need different requirements for charms.

A workaround for now while we're figuring out the correct action would be to shorten the summary in metadata.yaml

**Comment by ca-scribner** [comment]
Thanks @lengau for the quick update!

The workaround is appreciated, although its kinda awkward since we've already got charms in the field with these summaries.  I guess this was something introduced recently to align with how snapcraft handles things?  

Although the workaround is trivial, this is a breaking change that might deserve some deprecation notice/a more prominent version bump before promotion (if the restriction is kept at all).  My guess is that we'll find more of these longer summaries as we rebuild some other charms.  Not the end of the world, but something that would be good to know about long enough ahead to plan for it.

**Comment by lengau** [comment]
@ca-scribner what's currently in `latest/edge` is what's planned to be 3.0, so if/when it's released it will have a changelog with breaking changes listed. There will be quite a few breaking changes, but whether this is one of them is still up in the air.

I'm researching what real-world limitations there are for summary strings so I can adjust the model accordingly.

**Comment by lengau** [comment]
Follow-up from the store team:

Snap store has a 128 character limit for snap summaries, charmhub currently has no limit. 180 charms exceed 78 characters in summaries.

I've asked about how many exceed 128 characters and what the longest current summary is - ideally we'd support all existing charms, but if there's an outlier with an unreasonable length summary we might choose to break one or two charms. 180 is unacceptable for what goes into beta/stable though.

**Comment by lengau** [comment]
Okay! Sounds like **200 characters** is a reasonable maximum.

## WHEN WORKING THIS BUG:

whoever works this bug should also open PRs/MRs for the following to make sure their summaries are short enough:

* https://charmhub.io/snap-store-proxy
* https://charmhub.io/magma-access-gateway-operator
* https://charmhub.io/kubernetes-autoscaler
