### ISSUE TITLE
`failed to run apt update` on simultaneous builds

### ISSUE THREAD

**Issue by DnPlas** [canonical/charmcraft#1659]
### Bug Description

Charms that require apt packages installations (e.g. via `build-packages` in `chramcraft.yaml`) and are built simultaneously in the same machine tend to error out because the apt lock file is held by the first charm that gets built. This results in the following error:

```
2024-04-19 07:48:12.846 Executing: ['apt-get', 'update']
2024-04-19 07:48:13.004 :: Reading package lists...
2024-04-19 07:48:13.009 :: E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
```

Please note this behaviour is not exclusive to this process, simultaneous builds can yield other errors like https://github.com/canonical/charmcraft/issues/1132. I wonder if the long term solution is to re-evaluate the support for builds under these conditions.

### To Reproduce

1. Clone [this repo](https://github.com/canonical/kfp-operators)
2. Run the integration tests (this will build ALL the charms in the repo simultaneously)" 

`tox -e bundle-integration-${{ matrix.sdk }} -- --model kubeflow --bundle=./tests/integration/bundles/kfp_latest_edge.yaml.j2`

3. Wait for the error to happen.

### Environment

* Ubuntu 20.04 and later
* juju 3.x
* charmcraft `latest/candidate`
* lxd `latest/stable`

### charmcraft.yaml

It doesn't apply, there are multiple charms being built. 
You can find each charmcraft file in kfp-operators/charms/kfp-*/charmcraft.yaml

### Relevant log output

https://pastebin.canonical.com/p/Vrr7fPr2jB/

**Comment by mr-cal** [comment]
Thanks for the report, it does look like the [`build-packages`](https://github.com/canonical/kfp-operators/pull/436/files#diff-299b3225b87c152ce5b6b2dad0717521adbc2a284960969d6fd9052c66e0aa32R18) is what exposed this issue.

I think the problem is building multiple charms in destructive mode. We could patch craft-parts to wait for `apt` locks around [here](https://github.com/canonical/craft-parts/blob/2b16c15d81e9ed6ffef6a3d1074b6482953cd38c/craft_parts/packages/deb.py#L484), but then the more complications will follow.  For example, different builds may install different versions of packages, require conflicting packages, or add packages from other architectures. 

The right solution for building multiple charms in parallel is to use build environments.  All the issues [here](https://github.com/canonical/kfp-operators/blob/e32222f60d314e76859e999470c680801b9ed45a/.github/workflows/integrate.yaml#L145) have been resolved.  If it is not working, can you please create new issues in github?

**Comment by DnPlas** [comment]
hey @mr-cal thanks for the follow up!

I observe this behaviour w/o `destructive mode`, in fact using destructive mode yields a different issue. I have provided steps to reproduce in the description of this issue w/o destructive mode, so you should be able to reproduce, even outside of a Github/CI environment.

> The right solution for building multiple charms in parallel is to use build environments. All the issues [here](https://github.com/canonical/kfp-operators/blob/e32222f60d314e76859e999470c680801b9ed45a/.github/workflows/integrate.yaml#L145) have been resolved. If it is not working, can you please create new issues in github?

Please ignore that file as the behaviour I am describing is not using this file at all, and that comment is outdated.

**Comment by mr-cal** [comment]
Thanks for those extra details.  I'll try to reproduce it locally and see what I can find.

**Comment by mr-cal** [comment]
I wonder if it would be simpler to reproduce directly with pytest-operator

**Comment by mr-cal** [comment]
Great, glad to hear it's working!
