### ISSUE TITLE
init and build: a complete and sane project bootstrap but not buildable

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#247]
`charmcraft init` should provide a complete and sane project: it should work in theory, and tests should pass.

At the same time, `charmcraft build` (or `pack` in the future) should not build a project which is just bootstrapped from `init` and not paid attention nor care from the developer.

To get to that situation, we will:

- fix templates left by `init`, so tests pass ok
- mark with a comment using an unusual token (e.g.: `TEMPLATE-TODO`) all those corners where the developer needs to work to get started a real project.
- check if any of those tokens are leftovers when `build`ing, and refuse to build if any of those are present (indicating which one(s))

**Comment by mthaddon** [comment]
I think this may be an issue again. I just tried running `charmcraft init` and then deploying on rc11 and got:
```
mthaddon@tenaya:~/repos/k8s-charms$ mkdir charm-test
mthaddon@tenaya:~/repos/k8s-charms$ cd charm-test
mthaddon@tenaya:~/repos/k8s-charms/charm-test$ charmcraft init
Charm operator package file and directory tree initialized.
TODO: 

      README.md: Describe your charm in a few paragraphs of Markdown
      README.md: Provide high-level usage, such as required config or relations
   actions.yaml: change this example to suit your needs.
    config.yaml: change this example to suit your needs.
  metadata.yaml: fill out the charm's description
  metadata.yaml: fill out the charm's summary
  metadata.yaml: change to an Ubuntu series if not using k8s
   src/charm.py: change this example to suit your needs.
   src/charm.py: change this example to suit your needs.
mthaddon@tenaya:~/repos/k8s-charms/charm-test$ charmcraft build
Created 'charm-test.charm'.
mthaddon@tenaya:~/repos/k8s-charms/charm-test$ juju add-model charm-test
Added 'charm-test' model on microk8s/localhost with credential 'microk8s' for user 'admin'
mthaddon@tenaya:~/repos/k8s-charms/charm-test$ juju status
Model       Controller          Cloud/Region        Version   SLA          Timestamp
charm-test  microk8s-localhost  microk8s/localhost  2.9-rc11  unsupported  09:40:26+02:00

Model "admin/charm-test" is empty.
mthaddon@tenaya:~/repos/k8s-charms/charm-test$ juju deploy ./charm-test.charm
ERROR series with metadata v2 not valid
```

**Comment by manadart** [comment]
This is the issue as it stands from Juju's perspective.

Once a charm blob is acquired, Juju needs to determine whether the metadata is V1 or V2. Prior to the relocation of `bases` to _manifest.yaml_, this was done by detecting the presence of `bases` in _metadata.yaml_.

All pretty much axiomatic at this point - all charmer driven because the author determines the contents of _metadata.yaml_.

This determination does not change now that `bases` are relocated; Juju just looks at _manifest.yaml_ instead. **But** if the build process _always_ adds a manifest with `bases`, Juju loses the ability to determine V1 vs V2 format.

Note that Juju cannot rely on the presence of `series` to determine if metadata is definitely V1, because `series` was always optional - it can be V1 without `series`.

**Comment by jameinel** [comment]
I think we talked through whether we could rely on series: and dug through
published charms. There seems to be only one very old charm (only supports
trusty).
So going with series as the determinant for 2.9.0 feels like an appropriate
step.

**Comment by SimonRichardson** [comment]
@jameinel the following shows all the charms in charmhub that are currently series-less https://paste.ubuntu.com/p/x5d9rbWK59/
