### ISSUE TITLE
Charmcraft should validate all yaml files when building a charm

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#310]
Yesterday i added a buggy action to our charms. This was the problematic part, in our `actions.yaml`:
```
foo:
  title: 'Runs foo."
```

Charmcraft successfully built the charm. No warnings/errors given.

But when deploying a bundle that uses this charm, I got this message:

```bash
$ juju deploy ./bundle.yaml
ERROR cannot deploy bundle: yaml: line 60: found unexpected end of stream
```

Our CI was failing with the same message. I had no idea how to debug this. Our bundle has 30 lines, the error was on line 60 (?)...

Charmcraft should validate all charm files before building the charm. A message like `ERROR invalid actions.yaml` would be great.

**Comment by jameinel** [comment]
In this particular case, I think you have 'almost valid yaml', where you
open with a single quote, and everything beyond until the end of the file
is treated as just string content. Which is why the error is at 'line 60'
because you didn't close your string.
I agree that having charmcraft build just ensure that all the .yaml files
are valid yaml is reasonable. I think there is a request from charmcraft
such that Juju could actually validate according to a schema, rather than
trying to map Juju's schema in charmcraft. But it could certainly just try
to safe_load the yaml and make sure it is properly formatted.

**Comment by facundobatista** [comment]
This is implemented already. It runs automatically on building time, and the `analyze` command can be used to explicitly test it.

**Comment by facundobatista** [comment]
We'll create two linters, one for each file, that will only check that they are valid YAML files. No content will be verified. 

Related, there is #547 where it's being discussed what to check in `config,yaml` content.
