### ISSUE TITLE
Improve the "we recommend using charmcraft from snap" story

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#436]
We need to take several actions for this story to be more straightforward and users be less surprised:
- improve the project's README (which is shown both in Github and PyPI): it should declare this recommendation in a more prominent place, and inform that there are some caveats from running it as a developer, more info on the "docs page" (see next point)
- create a "doc page" (possible in the forum is enough) with several details about this recommendation:
    - we recommend the snap
    - on your own risk, you can run it using `CHARMCRAFT_DEVELOPER=1`
    - describe the potential problems (different `charmcraft` versions outside and inside the managed environment, different Pythons used, etc)
- Point to that doc page in the error message given to the user when `charmcraft` refuses to work for this situation

**Comment by sergiusens** [comment]
Installing
https://juju.is/t/installing-charmcraft/4776

Working with the newer Charmcraft
https://juju.is/t/charmcraft-bases-provider-support/4713

**Comment by sergiusens** [comment]
We have documentation about the snap but not reasons for why we chose it as the _best_ way to create a charm.

**Comment by knkski** [comment]
@sergiusens the documentation there covers the snap and installing from a copy of the git repo. It doesn't cover what happens when someone runs `pip install charmcraft` though. Since someone running `pip install charmcraft` is unlikely to be a charmcraft developer, they will probably not realize that they have to set `CHARMCRAFT_DEVELOPER=1`.

It would be nice if instead of `pip install charmcraft` installing a package that looks broken unless you know a special environment variable, it just failed immediately and refused to install. Something like this:

```
$ pip install charmcraft
Collecting charmcraft
  Downloading charmcraft-1.1.0-py3-none-any.whl (92 kB)
     |████████████████████████████████| 92 kB 1.0 MB/s

ERROR: The snap is the recommended way of installing charmcraft. If you'd like to install via pypi, set the `CHARMCRAFT_DEVELOPER=1` environment variable
```

**Comment by sergiusens** [comment]
We removed the requirement to have CHARMCRAFT_DEVELOPER set, so closing
