### ISSUE TITLE
charmcraft init --author do not populate the maintainers list in metadata.yaml

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#440]
`charmcraft init --author "Firstname Lastname"` do not populate the `maintainers` list in `metadata.yaml`. It would be nice to have it there as well.

**Comment by sergiusens** [comment]
This needs exploration.

**Comment by facundobatista** [comment]
Opened a question [in the forum in the metadata v2 reference](https://discourse.charmhub.io/t/charm-metadata-v2/3674/25) to understand how this would happen.

**Comment by facundobatista** [comment]
We discussed this, considering the purpose of the field, and what for and how it will be used, which is not 100% clear/defined yet.

So we won't put the charm's author here, mainly because this information is already known in Charmhub (the charm owner, the one who registered the charm's name) and that info can be used for display purposes. There's also the extra complexity of that we current have the first and last names of the author, but the info in that field should also include the email.

In consideration of all this, let's close this issue.

**Comment by heitorPB** [comment]
> considering the purpose of the field

What is the purpose of this field? And why the author can't be a maintainer?

> this information is already known in Charmhub

I think this is horrible. Part of the charm's metadata comes from `metadata.yaml` and some other fields come from CharmHub... this should not happen. But maybe that should be a discussion for the forums.
