### ISSUE TITLE
`charmcraft analyze` - check for invalid `config.yaml`

### ISSUE THREAD

**Issue by jnsgruk** [canonical/charmcraft#547]
Follow on from [canonical/operator#618](https://github.com/canonical/operator/pull/618). 

At present, it is possible to successfully `charmcraft pack` on a charm with an empty `config.yaml`, i.e. one that does not contain an `options:` map. Given that Juju will refuse to deploy a charm with such a `config.yaml`, we should probably try to catch this using the `charmcraft analyze` machinery that is invoked when a charm is packed.

As I understand, you can completely omit `config.yaml`, but if it exists it must have a top level key named `options`.

**Comment by heitorPB** [comment]
didn't https://github.com/canonical/charmcraft/issues/310 addressed that?

**Comment by ca-scribner** [comment]
I encountered this using charmcraft v1.2.1, which I think should include #310 so possibly not?

**Comment by facundobatista** [comment]
I reopened #310, it was incorrectly closed, as I just annotated there. But that's only on checking that it's a YAML file, no the content.

So please keep talking here and define what you'd want to be verified in `config.yaml`'s content.

**Comment by jnsgruk** [comment]
Thanks @facundobatista 

Feels like charmcraft should indeed validate the contents as sane YAML, but just not include it where it's empty?

- If `config.yaml` has config options defined under `options:` then validate the yaml and include
- If `config.yaml` has an `options:` map that is empty, don't include the file?
- If `config.yaml` doesn't have an `options:` map at all, don't include and output a warning/message?

**Comment by facundobatista** [comment]
Validation is one thing, including a file or not is totally different. I don't like the idea of start including files or not depending on their content: general rules will soon get out of control, and probably could be implemented using "parts lifecycle" functionality; in any case, I don't think we need it here.

And I say we don't need it here, because I think we should stick to the rule of "make the linter fail on a situation where juju will end up failing too", just to reduce the needed cycle to fix the charm.

So, if Juju fails on an empty `config.yaml` file, we should also fail (**unless** they think this is a bug and will fix the tool). Note that the [reference for this file](https://discourse.charmhub.io/t/creating-config-yaml-and-configuring-charms/1039) states that "If this file is used, it must contain a dictionary of options...".

IMO the rules for `config.yaml`, after reading the indicated reference, should be (starting from the base that it exists and is a valid YAML, which is covered by #310):
- must have an `options` key
- each of the items inside `options` must have a `type` key

**Comment by jnsgruk** [comment]
Agreed, that seems like a sane way forward. Thanks!
