### ISSUE TITLE
Can't build charm: Failed to build charm for bases index '0'

### ISSUE THREAD

**Issue by julianaklulo** [canonical/charmcraft#639]
I'm trying to build a charm using `charmcraft 1.4.0`, but it fails with the error `"Failed to build charm for bases index '0'"`.
I've build this charm before in this machine, also tried building it in another machine, but got the same error.

The log I get: https://paste.ubuntu.com/p/hfvnSzbxzx/

I appreciate any help with this!

**Comment by cmatsuoka** [comment]
This problem is caused by jinja2 requiring a version of setuptools that's newer than the one that's initially installed. Adding the following to you charmcraft.yaml should fix this issue:
```
parts:
    charm:
        charm-python-packages: [setuptools]
```
If you also need Tempita, the packing may fail if you use setuptools 58 or later. In this case limit the setuptools version by specifying `setuptools < 58`.

Also see https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158, and issue #632.

**Comment by cmatsuoka** [comment]
Please reopen if that doesn't solve your problem.

**Comment by pmatulis** [comment]
I hit this today (l[og](https://paste.ubuntu.com/p/MNvMsydW2Q/)). I build this charm back on Aug 5 of this year.
