### ISSUE TITLE
Packaging of charm and layer code

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#66]
With the move to fully embracing Python for writing charms in, it seems like we can also embrace the packaging infrastructure that Python has created, and package layers as regular Python packages. This has a few advantages:

1. Works with regular Python tooling, such as pip and virtualenv. IDEs also already know how to introspect code set up this way
1. Python developers don't have to learn a new way of packaging/importing layers, it's done exactly as they'd expect
1. We don't have to maintain something like https://github.com/juju/layer-index, it comes for free with the ability to publish layers to pypi.org. If we did ever want to host a pypi alternative, we could use the same code that pypi.org itself runs on.
1. Relying on existing tooling reduces the complexity of the charm build process, such as removing the need for a separate wheelhouse.txt.
1. We can build on top of existing dependency management tooling like pip/poetry, which already supports many different ways of grabbing dependencies, such as local paths (including from submodules), specific git commits, or pypi alternatives if we were to ever host a charming-specific pypi alternative.

This presents some issues with installing dependencies that could then be solved by packaging charm code as Python snaps. As rationale:

1. Layers are code that's consumed by other code as libraries, whereas charms are code that's consumed more like an application
1. Development can still use regular virtualenvs, since layers are just normal Python packages
1. Packaging charms for the charm store wouldn't run into virtualenv issues, they're installed as "system" packages inside the snap.
1. In both dev and production, dependencies are managed in a way that's not surprising to a Python developer
1. Reusing the snap tooling and infrastructure would cut down on a lot of work on the charming side of things

**Comment by facundobatista** [comment]
Hello @knkski !

Indeed this is something we're very interested in doing. We want for the new charms to be as pythonic as possible, which at some point translates to the tools and infrastructure used around the code.

For example, the current `build` command uses requirement files for the dependencies of the project (a single `requirements.txt` by default, but otherwise can be specified by command options if needed differently), using `pip` to ship those dependencies inside the charm zip file (**without** putting a Python interpreter inside, though).

Regarding "layers", the Operator Framework is moving more to the "components" side.

I'm closing this issue because I think we fullfil what's indicated here in one way or another. **Please** let's talk if there is something missing that you can think of. The best way of doing that is opening new issues here for any particular details.

Thank you!
