### ISSUE TITLE
Better charmcraft pack output

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charmcraft#737]
I know there's been recently some discussion on making the `charmcraft pack` output more informative, here's my two cents on it:

What I wish I'd see:

```
$ charmcraft pack
Launching environment... 
  base name='ubuntu' 
  channel='20.04' 
  architectures=['amd64'] 
[ ================>    ] ...done in 22.5 s.

Building dependencies (only required the first time you pack this charm)...
[ ================>    ] ...done in 45.5 s.

Packing...
[ ================>    ] ...done in 5.5 s.

All done in 1:35.5 m.
```

**Comment by facundobatista** [comment]
Hello! Thanks for the report.

Some details/questions:

- "Building dependencies", "Packing", etc, are "progress messages", and in `brief` verbosity level (the default) they will appear but later overwritten. But those appear in the `verbose` verbosity level (and more verbose modes), 
- are the `[======>  ]` progress bars? if yes, we cannot show this information because we don't know how much time will take each step
- what's the idea behind the times on each step? if the step already finished, what would you use those timings for? note that with `debug` verbosity level each line has a timestamp if you want to debug something specific.

Thanks!

**Comment by PietroPasotti** [comment]
Thanks for answering! It's been some time, and both charmcraft and my opinions have gone a long way, so I get your points and I  reply with:

- progress messages are good, although personally I don't like them being overwritten by default. I think the default should be more basic and allow you to see the history of the progress, not just 'what's happening right now'. But there's a big IMHO on this one.
- scratch the times, you're right.
- the progress bars, I can see there's no way to make them update live, but I still think some way of showing progress would be valuable.

How about:

- Launching a container... [step 1/7]
- Building dependencies... [step 2/7]
- Packing... [step 3/7]
...
- Cleaning up LXD... [step 7/7]
- Done.

**Comment by facundobatista** [comment]
It's been some time, yes, sorry for the delay, but I didn't want to lose the opportunity of getting your valuable opinion and see how I can improve the tool and your experience.

Having a sense of progress across all the needed steps would be nice. I'm not seeing that it's not possible, but it's extremely hard, because the different parts are kind of autonomous... for example, charmcraft needs an instance to pack, and that may be one or three/four steps according to the previous state of the instance for that charm. 

Or, a more complicated case, the lifecycle process involves several steps for the different parts defined in charmraft.yaml, and all that happens inside the Craft Parts library (not only which steps would be initially required for the different configured parts, but also which steps could be skipped because the library decides that "the current state of the files in disk" (after running that step for that part in a previous `pack` operation) is good enough.

Anyway, I'll keep in mind how can we give a sense of progress across the whole operation.

**Comment by PietroPasotti** [comment]
Indeed! Sometimes it's hard to guess whether it's stuck or just busy doing some work.

**Comment by facundobatista** [comment]
But having a "overall progress view" won't help us with that.

For example, we see...

- Launching a container... [step 1/7]

... and it stays with that message for a couple of minutes, will not give us any idea if LXD is downloading a new image on a temporarily flaky connection and will finish and continue OK some seconds from now or is plainly stuck somewhere...

**Comment by lengau** [comment]
Charmcraft follows the general starcraft guidelines for its UX so I'm going to close this. If you have suggestions for how to improve it overall for charmcraft, snapcraft, rockcraft, etc., please open an issue in [craft-cli](https://github.com/canonical/craft-cli). If you have more specific requests about charmcrafts UX, please feel free to raise new issues about them.
