### ISSUE TITLE
Packing bundle fails in the presence of a venv

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#829]
## Issues
- When a `venv` folder exists in a bundle dir, packing fails.
- When a `build` folder exists in a bundle dir, packing fails.
- `charmcraft clean` doesn't work for bundles.

Charmcraft version 2.0.0

## Description

`charmcraft pack` for a bundle failed for

```
Execute action
execute action bundle:Action(part_name='bundle', step=Step.BUILD, action_type=ActionType.RUN, reason=None, project_vars=None)
remove directory /home/ubuntu/code/cos-lite-bundle/build/parts/bundle/build
:: + mkdir -p /home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install
:: + cp --archive --link --no-dereference CONTRIBUTING.md LICENSE README.md bundle.yaml bundle.yaml.j2 charmcraft.yaml overlays pyproject.toml render_bundle.py tests tox.ini venv /home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install
:: cp: cannot create hard link '/home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install/venv/bin/python' to 'venv/bin/python': Operation not permitted
:: cp: cannot create hard link '/home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install/venv/bin/python3' to 'venv/bin/python3': Operation not permitted
:: cp: cannot create hard link '/home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install/venv/bin/python3.10' to 'venv/bin/python3.10': Operation not permitted
:: cp: cannot create hard link '/home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install/venv/bin/python3.9' to 'venv/bin/python3.9': Operation not permitted
Parts processing error: Failed to run the build script for part 'bundle'.
```

After removing the `venv` folder, packing failed for

```
2022-08-12 11:28:45.362 Execute action
2022-08-12 11:28:45.362 execute action bundle:Action(part_name='bundle', step=Step.BUILD, action_type=ActionType.RUN, reason=None, project_vars=None)
2022-08-12 11:28:45.365 remove directory /home/ubuntu/code/cos-lite-bundle/build/parts/bundle/build
2022-08-12 11:30:25.625 :: + mkdir -p /home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install
2022-08-12 11:30:25.627 :: + cp --archive --link --no-dereference CONTRIBUTING.md LICENSE README.md bundle.yaml bundle.yaml.j2 charmcraft.yaml overlays pyproject.toml render_bundle.py tests tox.ini venv /home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install
2022-08-12 11:30:25.628 :: cp: cannot create hard link '/home/ubuntu/code/cos-lite-bundle/build/parts/bundle/install/CONTRIBUTING.md' to 'CONTRIBUTING.md': File exists
```

`charmcraft clean` failed for

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/code/cos-lite-bundle/metadata.yaml'
```

Packing succeeded after `rm -rf build`.

[cc.log](https://github.com/canonical/charmcraft/files/9321105/cc.log)

**Comment by facundobatista** [comment]
Hello! Thanks fro the report.

Let's me address your points starting from the last one, for simplicity:

- `charmcraft clean` works for *managed instances*; so if you built using LXD or Mulitpass, `clean` will work on those instances where something was built previously. So, if you pack a charm using `--destructive-mode`, or a bundle (where nothing is compiled, so no managed instance is used), the "clean" will not do anything. Note that Charmcraft cannot go and remove the "build" directory, because there is no way to know if that directory is actually the result of the build or just an user's directory (or the former, but with more content from the user)

- `pack` works normally ok if the `build` directory is there, and even reuses it to speed up the subsequent builds; the problem in your case if I understand correctly is that some problematic files are leftover in the build tree (because last failure) and finding/using those is what brings new failures; the solution here is to remove the build directory (in this case, not regularly after each pack)

- let's talk about why it's failing for with the `venv` directory, then... I couldn't reproduce it here: I just created a virtualenv (`python3 -m venv venv`) and then packed the bundle, it succeeded (note that the `venv` directory is not included into the packed bundle). So, could you provide more information around your bundle structure? thanks!!!!

**Comment by sed-i** [comment]
Thanks for the details @facundobatista.
I retried this and was unable to reproduce on a 22.04 host

```shell
git clone https://github.com/canonical/cos-lite-bundle.git
cd cos-lite-bundle
virtualenv -p python3 venv
source venv/bin/activate
pip install jinja2
./render_bundle.py bundle.yaml --channel=edge
charmcraft pack
```

nor 22.04/20.04 VMs.

```shell
multipass launch jammy --cpus=1 --mem=2G
multipass shell abundant-marmoset
sudo snap install charmcraft --classic
lxd init --auto
sudo apt update
sudo apt install python3-virtualenv
```

Closing.
