### ISSUE TITLE
Better User facing message when credentials not found

### ISSUE THREAD

**Issue by omnivector-kelly** [canonical/charmcraft#843]
Example:
`charmcraft upload-resource my-charm resource --filepath=/blah`
outputs
`charmcraft internal error: InitError('Failed to create the collection: Prompt dismissed..')
Full execution log: /home/<username>/snap/charmcraft/common/cache/charmcraft/log/charmcraft-<datetime>.log`

We need to use --verbose to see the login problem. It would be nice to have the output surface the core issue to the front.

Example of verbose output:
`charmcraft upload-resource my-charm resource --filepath=/blah --verbose
Starting charmcraft version 2.0.0
Logging execution to '/home/<username>/snap/charmcraft/common/cache/charmcraft/log/charmcraft-<datetime>.log
Uploading resource directly from file '/blah'.
Starting to push '/blah'
Uploading... (--->)
Uploading... (<---)
Credentials not found. Trying to log in...
charmcraft internal error: InitError('Failed to create the collection: Prompt dismissed..')
Full execution log: '/home/<username>/snap/charmcraft/common/cache/charmcraft/log/charmcraft-<datetime>.log'`

**Comment by facundobatista** [comment]
Hello! Thanks for the report!

This situation does not comes from Craft Store library not finding the credentials, but crashing when trying to use the underlying keyring system. So we cannot improve the message here, it's a crash for a particular situation that needs to be handled better in Craft Store.

The library [already has an issue to track this](https://github.com/canonical/craft-store/issues/58), so I'm closing this issue here. 

Thanks again!
